In [41]:
%load_ext autoreload
%autoreload 2
import os
import numpy as np
import timeit
from models import *
from equations import *
from solvers import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:
data_file_name = "data.npz"
params = ModelParams.load_from_npz(data_file_name)
model = Model(params)
shocks = model.shocks

In [43]:
model.params.tilde_tau.max()

np.float64(1.915345393)

In [44]:
solver = ModelSolver(model)
solver.solve()

Iter 1: w_min=9.947e-01, w_max=1.002e+00, X_min=1.760e+03, X_max=4.828e+09, Δw=5.310e-03, ΔP=2.220e-16
Iter 2: w_min=9.906e-01, w_max=1.003e+00, X_min=1.759e+03, X_max=4.833e+09, Δw=4.097e-03, ΔP=3.585e-03
Iter 3: w_min=9.878e-01, w_max=1.004e+00, X_min=1.758e+03, X_max=4.838e+09, Δw=2.755e-03, ΔP=3.442e-03
Iter 4: w_min=9.862e-01, w_max=1.004e+00, X_min=1.757e+03, X_max=4.842e+09, Δw=1.645e-03, ΔP=2.808e-03
Iter 5: w_min=9.853e-01, w_max=1.004e+00, X_min=1.756e+03, X_max=4.845e+09, Δw=8.649e-04, ΔP=1.966e-03
Iter 6: w_min=9.849e-01, w_max=1.004e+00, X_min=1.756e+03, X_max=4.847e+09, Δw=4.401e-04, ΔP=1.227e-03
Iter 7: w_min=9.848e-01, w_max=1.005e+00, X_min=1.755e+03, X_max=4.849e+09, Δw=2.945e-04, ΔP=7.866e-04
Iter 8: w_min=9.848e-01, w_max=1.005e+00, X_min=1.755e+03, X_max=4.849e+09, Δw=2.733e-04, ΔP=4.984e-04
Iter 9: w_min=9.849e-01, w_max=1.005e+00, X_min=1.755e+03, X_max=4.850e+09, Δw=1.996e-04, ΔP=3.103e-04
Iter 10: w_min=9.850e-01, w_max=1.005e+00, X_min=1.755e+03, X_max=4.850e+

In [45]:
model.sol.w_hat

array([1.00487287, 1.00025114, 0.99697138, 0.99321673, 0.99808464,
       0.99595041, 0.99338436, 0.98885243, 0.99426271, 0.99663022,
       0.99658891, 0.99684319, 0.99505486, 0.99818777, 0.99951223,
       0.99243071, 0.99628666, 1.00057927, 0.9966398 , 0.99593293,
       0.99722894, 1.00065737, 0.99301181, 1.00293684, 0.99960175,
       0.99439621, 0.98737658, 0.98508414, 1.0022247 , 0.99773342,
       0.99672645, 0.99637068, 0.99658095, 0.99559804, 0.99802976,
       0.99610933, 1.00355008])

In [54]:
sector_list[target_sectors_index[0]]

np.str_('Metal Products')

In [55]:
# Counterfactual Tariff: U.S.
# U.S.: impose uniform 25% tariff on all imported aluminum products 
target_importers = ['USA']  # one or multiple
country_list = list(params.country_list)
sector_list = list(params.sector_list)
target_importers_index = [country_list.index(importer) for importer in target_importers]  

target_sectors = ['Metal Products']  # one or multiple
target_sectors_index = [sector_list.index(sector) for sector in target_sectors]  

counter_tariff = params.tilde_tau.copy()

for importer_index in target_importers_index:
    for exporter_index in range(len(country_list)):
        for sector_index in target_sectors_index:
            # avoid domestic tariff
            if importer_index != exporter_index:
                counter_tariff[importer_index, exporter_index, sector_index] += 0.25

params.tilde_tau = counter_tariff

model_new = Model(params)
solver = ModelSolver(model_new)
solver.solve()


Iter 1: w_min=9.946e-01, w_max=1.002e+00, X_min=1.760e+03, X_max=4.835e+09, Δw=5.380e-03, ΔP=2.220e-16
Iter 2: w_min=9.905e-01, w_max=1.003e+00, X_min=1.759e+03, X_max=4.842e+09, Δw=4.163e-03, ΔP=3.634e-03
Iter 3: w_min=9.876e-01, w_max=1.004e+00, X_min=1.758e+03, X_max=4.848e+09, Δw=2.813e-03, ΔP=3.494e-03
Iter 4: w_min=9.860e-01, w_max=1.004e+00, X_min=1.757e+03, X_max=4.853e+09, Δw=1.692e-03, ΔP=2.861e-03
Iter 5: w_min=9.851e-01, w_max=1.005e+00, X_min=1.756e+03, X_max=4.856e+09, Δw=9.005e-04, ΔP=2.014e-03
Iter 6: w_min=9.846e-01, w_max=1.005e+00, X_min=1.755e+03, X_max=4.859e+09, Δw=4.615e-04, ΔP=1.268e-03
Iter 7: w_min=9.845e-01, w_max=1.005e+00, X_min=1.755e+03, X_max=4.860e+09, Δw=3.003e-04, ΔP=8.209e-04
Iter 8: w_min=9.845e-01, w_max=1.006e+00, X_min=1.755e+03, X_max=4.861e+09, Δw=2.661e-04, ΔP=5.204e-04
Iter 9: w_min=9.846e-01, w_max=1.006e+00, X_min=1.755e+03, X_max=4.862e+09, Δw=1.975e-04, ΔP=3.269e-04
Iter 10: w_min=9.846e-01, w_max=1.006e+00, X_min=1.755e+03, X_max=4.863e+

In [58]:
model_new.sol.pim_prime

array([[[8.58026441e-01, 4.99195171e-01, 7.74185267e-01, ...,
         9.88579081e-01, 9.26160277e-01, 9.96578988e-01],
        [2.48547719e-03, 2.10949319e-03, 9.76397170e-03, ...,
         3.65896364e-03, 1.45120030e-02, 3.88175916e-06],
        [5.01002159e-04, 4.70523154e-04, 1.60189841e-03, ...,
         1.46221700e-04, 1.14670504e-04, 2.09805908e-04],
        ...,
        [9.36481482e-07, 5.89710683e-07, 3.33875720e-05, ...,
         4.32363665e-06, 5.13249606e-05, 2.77814803e-06],
        [8.95408543e-06, 1.13685715e-06, 2.52061047e-05, ...,
         9.58756066e-06, 9.20136703e-05, 5.26915443e-06],
        [9.10681487e-02, 3.57002604e-01, 8.54727181e-02, ...,
         5.60600871e-03, 5.63490183e-02, 3.07764719e-03]],

       [[7.16392560e-03, 5.13736651e-03, 4.90830886e-03, ...,
         4.34516461e-03, 1.54991320e-02, 3.39347293e-01],
        [9.29588433e-01, 8.31552923e-01, 9.58202906e-01, ...,
         9.56688542e-01, 8.12383695e-01, 9.07992250e-04],
        [2.79792843e-04, 

In [62]:
percent_change = (model_new.sol.pim_prime - model.sol.pim_prime) / model.sol.pim_prime
percent_change[0, 1, 6]

np.float64(0.004566010368297583)

In [23]:
(model_new.sol.w_hat - model.sol.w_hat) / model.sol.w_hat

array([ 0.00110273, -0.00016643, -0.00015593, -0.0001932 , -0.00046083,
       -0.00019513, -0.00021348, -0.00029328, -0.00023174, -0.00107853,
       -0.00011304, -0.00029413, -0.00035046, -0.00029651, -0.00069871,
       -0.00077597, -0.00031171, -0.00020079, -0.00025064, -0.00023172,
       -0.00020635, -0.00020049, -0.00027201, -0.00101192, -0.00022218,
       -0.0002279 , -0.00023938, -0.00067271, -0.00015514, -0.00021735,
       -0.00019681, -0.00023101, -0.00044819, -0.0002868 , -0.00021984,
       -0.00026697, -0.00070431])