In [57]:
%load_ext autoreload
%autoreload 2
import os
import numpy as np
import timeit
from models import *
from equations import *
from solvers import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [58]:
data_file_name = "experiments/toy_IO/params.npz"
params = ModelParams.load_from_npz(data_file_name)
# params.theta = np.array([2, 2])
model = Model(params)
shocks = model.shocks
initial_guess = 1.5
model.sol.w_hat *= initial_guess
print("Initial guess for w_hat:", model.sol.w_hat)
solver = ModelSolver(model, config=SolverConfig(reduced=False, method="Nelder-Mead"))
# solver = ModelSolver(model, config=SolverConfig(reduced=False, method="Powell"))
solver.solve()

Initial guess for w_hat: [1.5 1.5]
[FULL] Iter 1: loss = 3.167e+03
[FULL] Iter 2: loss = 8.423e+03
[FULL] Iter 3: loss = 3.561e+03
[FULL] Iter 4: loss = 1.232e+03
[FULL] Iter 5: loss = 1.855e+03
[FULL] Iter 6: loss = 8.233e+02
[FULL] Iter 7: loss = 6.128e+02
[FULL] Iter 8: loss = 4.440e+02
[FULL] Iter 9: loss = 1.385e+02
[FULL] Iter 10: loss = 5.250e+01
[FULL] Iter 11: loss = 6.319e+01
[FULL] Iter 12: loss = 2.554e+01
[FULL] Iter 13: loss = 1.280e+01
[FULL] Iter 14: loss = 1.554e+01
[FULL] Iter 15: loss = 5.686e+00
[FULL] Iter 16: loss = 8.430e+00
[FULL] Iter 17: loss = 2.869e+00
[FULL] Iter 18: loss = 5.613e+00
[FULL] Iter 19: loss = 7.226e-01
[FULL] Iter 20: loss = 1.196e+00
[FULL] Iter 21: loss = 9.548e-01
[FULL] Iter 22: loss = 5.402e-01
[FULL] Iter 23: loss = 1.617e-01
[FULL] Iter 24: loss = 3.441e-01
[FULL] Iter 25: loss = 1.436e-01
[FULL] Iter 26: loss = 1.585e-01
[FULL] Iter 27: loss = 5.305e-03
[FULL] Iter 28: loss = 2.019e-02
[FULL] Iter 29: loss = 6.544e-02
[FULL] Iter 30: l

/Users/yaolangzhong/Dropbox/Carbon_Emission_Analysis_2017/volatility_analysis/solvers.py:199: OptimizeWarning: Unknown solver options: gtol
  res = minimize(


In [46]:
solver.res

       message: Optimization terminated successfully.
       success: True
        status: 0
           fun: 15.367772090815606
             x: [ 1.082e+00  1.082e+00]
           nit: 60
          nfev: 117
 final_simplex: (array([[ 1.082e+00,  1.082e+00],
                       [ 1.082e+00,  1.082e+00],
                       [ 1.082e+00,  1.082e+00]]), array([ 1.537e+01,  1.537e+01,  1.537e+01]))

In [48]:
(N, S, alpha, beta, gamma, theta, pif, pim, tilde_tau,
             Xf, Xm, V, D, countries, sectors) = params.unpack()
(lambda_hat, df_hat, dm_hat, tilde_tau_prime) = shocks.unpack()
(w_hat, c_hat, Pf_hat, Pm_hat, pif_hat, pim_hat, Xf_prime,
             Xm_prime, p_index, real_w, D_prime) = model.sol.unpack()
pim_prime = pim * pim_hat
pif_prime = pif * pif_hat


In [49]:
# c_hat, Pm_hat = solve_price_and_cost(w_hat, beta, gamma, theta, pim, lambda_hat, dm_hat)
# # 2. Final-goods price index
# Pf_hat = calc_Pf_hat(c_hat, theta, pif, lambda_hat, df_hat)
# # 3. Expenditure-share changes
# pif_hat = calc_pif_hat(c_hat, Pf_hat, theta, lambda_hat, df_hat)
# pim_hat = calc_pim_hat(c_hat, Pm_hat, theta, lambda_hat, dm_hat)
# # 4. Updated bilateral shares
# pif_prime = pif * pif_hat
# pim_prime = pim * pim_hat
# # 5. τ (needed for linear system)
# N, S = alpha.shape
# # 6. Solve linear system for quantities and trade balance
# #Xf_prime, Xm_prime, D_prime = calc_Xf_Xm_D(N, S, alpha, gamma, pif_prime, pim_prime,tilde_tau_prime, w_hat, V)
# Xf_prime_iterative, Xm_prime_iterative, D_prime_iterative = \
# calc_Xf_Xm_D_iterative(N, S, alpha, gamma, pif_prime, pim_prime,tilde_tau_prime, w_hat, V)
# Xf_prime_iterative_python, Xm_prime_iterative_python, D_prime_iterative_python = \
# calc_Xf_Xm_D_iterative_python(N, S, alpha, gamma, pif_prime, pim_prime,tilde_tau_prime, w_hat, V, Xf0=Xf, Xm0=Xm, D0=D)

In [50]:
assert np.allclose(pif_prime.sum(axis=1), 1.0, atol=1e-10)
assert np.allclose(pim_prime.sum(axis=1), 1.0, atol=1e-10)

In [51]:
pim_prime

array([[[0.50012132, 0.50012132],
        [0.49987648, 0.49987648]],

       [[0.50012132, 0.50012132],
        [0.49987648, 0.49987648]]])

In [52]:
w_hat

array([1.08188551, 1.08202427])

In [53]:
c_hat

array([[1.08191676, 1.08191676],
       [1.08199244, 1.08199244]])

In [54]:
Xf_prime, Xf

(array([[54.93704739, 54.93704739],
        [74.89753911, 74.89753911]]),
 array([[50., 50.],
        [70., 70.]]))

In [55]:
Xm_prime, Xm

(array([[54.09561473, 54.09561473],
        [54.09561473, 54.09561473]]),
 array([[60., 60.],
        [60., 60.]]))

In [56]:
D_prime, D

(array([-20.01876878,  20.01876878]), array([-20.,  20.]))

In [13]:
w_hat, c_hat, Pf_hat, Pm_hat, pif_hat, pim_hat, Xf_prime,

(array([1.00130203, 1.00167197]),
 array([[1.00138583, 1.00138583],
        [1.00158762, 1.00158762]]),
 array([[1.00148671, 1.00148671],
        [1.00148671, 1.00148671]]),
 array([[1.00148641, 1.00148641],
        [1.00148641, 1.00148641]]),
 array([[[1.00020149, 1.00020149],
         [0.99979851, 0.99979851]],
 
        [[1.00020149, 1.00020149],
         [0.99979851, 0.99979851]]]),
 array([[[1.00020088, 1.00020088],
         [0.9997979 , 0.9997979 ]],
 
        [[1.00020088, 1.00020088],
         [0.9997979 , 0.9997979 ]]]),
 array([[50.11141529, 50.11141529],
        [70.06702507, 70.06702507]]))